version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: "org.jetbrains.compose.*"
      - dependency-name: "org.jetbrains.androidx.*"
      # Should be updated together with AGP
      - dependency-name: "gradle-wrapper"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/website"
    open-pull-requests-limit: 99
    schedule:
      interval: "monthly"
    groups:
      angular:
        patterns:
          - "@angular/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "postcss"
          - "@tailwindcss/postcss"
